# -*- encoding: utf-8 -*-

=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.0
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

$:.push File.expand_path('lib', __dir__)

# 🛡️ Resilient version loading (Fixes "Chicken & Egg" bootstrap errors)
begin
  require "alogram_payrisk/version"
  VERSION = AlogramPayRisk::VERSION
rescue LoadError
  # Fallback: Read version from RELEASE.json if lib is not yet generated
  require 'json'
  release_file = File.expand_path("RELEASE.json", __dir__)
  if File.exist?(release_file)
    VERSION = JSON.parse(File.read(release_file))["version"]
  else
    VERSION = "0.0.0.bootstrap"
  end
end

Gem::Specification.new do |s|
  s.name        = "alogram_payrisk"
  s.version     = VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Alogram Engineering"]
  s.email       = ["packages@alogram.ai"]
  s.homepage    = "https://www.alogram.ai"
  s.summary     = "Alogram PayRisk Ruby SDK"
  s.description = "A Ruby wrapper for the Alogram PayRisk API."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'httpx', '~> 1.0', '>= 1.0.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'parallel', '~> 1.22'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
