=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.2
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Proof of delegation for an autonomous shopping agent (UCP/MCP compatible).  Allows PayRisk to verify the \"Who\" and \"Trust\" behind a machine-driven transaction. 
  class AgentManifest < ApiModelBase
    attr_accessor :provider

    # Specific model version of the agent.
    attr_accessor :model

    # Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Supports \"ecid_\" slugs (Legacy) or \"cus_\" hex (Preferred). 
    attr_accessor :principal_id

    # Platform-provided reputation score for the agent.
    attr_accessor :trust_tier

    # Authorized scope of authority for the agent.
    attr_accessor :capabilities

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'provider' => :'provider',
        :'model' => :'model',
        :'principal_id' => :'principalId',
        :'trust_tier' => :'trustTier',
        :'capabilities' => :'capabilities'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'provider' => :'AgentProvider',
        :'model' => :'String',
        :'principal_id' => :'String',
        :'trust_tier' => :'Float',
        :'capabilities' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::AgentManifest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::AgentManifest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      else
        self.provider = nil
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = nil
      end

      if attributes.key?(:'principal_id')
        self.principal_id = attributes[:'principal_id']
      else
        self.principal_id = nil
      end

      if attributes.key?(:'trust_tier')
        self.trust_tier = attributes[:'trust_tier']
      else
        self.trust_tier = nil
      end

      if attributes.key?(:'capabilities')
        if (value = attributes[:'capabilities']).is_a?(Array)
          self.capabilities = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @provider.nil?
        invalid_properties.push('invalid value for "provider", provider cannot be nil.')
      end

      if @model.nil?
        invalid_properties.push('invalid value for "model", model cannot be nil.')
      end

      if @principal_id.nil?
        invalid_properties.push('invalid value for "principal_id", principal_id cannot be nil.')
      end

      if @principal_id.to_s.length > 100
        invalid_properties.push('invalid value for "principal_id", the character length must be smaller than or equal to 100.')
      end

      if @principal_id.to_s.length < 6
        invalid_properties.push('invalid value for "principal_id", the character length must be greater than or equal to 6.')
      end

      pattern = Regexp.new(/^(ecid_[a-z0-9\-_]{2,96}|cus_[a-f0-9]{32})$/)
      if @principal_id !~ pattern
        invalid_properties.push("invalid value for \"principal_id\", must conform to the pattern #{pattern}.")
      end

      if @trust_tier.nil?
        invalid_properties.push('invalid value for "trust_tier", trust_tier cannot be nil.')
      end

      if @trust_tier > 1.0
        invalid_properties.push('invalid value for "trust_tier", must be smaller than or equal to 1.0.')
      end

      if @trust_tier < 0.0
        invalid_properties.push('invalid value for "trust_tier", must be greater than or equal to 0.0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @provider.nil?
      return false if @model.nil?
      return false if @principal_id.nil?
      return false if @principal_id.to_s.length > 100
      return false if @principal_id.to_s.length < 6
      return false if @principal_id !~ Regexp.new(/^(ecid_[a-z0-9\-_]{2,96}|cus_[a-f0-9]{32})$/)
      return false if @trust_tier.nil?
      return false if @trust_tier > 1.0
      return false if @trust_tier < 0.0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] provider Value to be assigned
    def provider=(provider)
      if provider.nil?
        fail ArgumentError, 'provider cannot be nil'
      end

      @provider = provider
    end

    # Custom attribute writer method with validation
    # @param [Object] model Value to be assigned
    def model=(model)
      if model.nil?
        fail ArgumentError, 'model cannot be nil'
      end

      @model = model
    end

    # Custom attribute writer method with validation
    # @param [Object] principal_id Value to be assigned
    def principal_id=(principal_id)
      if principal_id.nil?
        fail ArgumentError, 'principal_id cannot be nil'
      end
      if principal_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "principal_id", the character length must be smaller than or equal to 100.'
      end

      if principal_id.to_s.length < 6
        fail ArgumentError, 'invalid value for "principal_id", the character length must be greater than or equal to 6.'
      end

      pattern = Regexp.new(/^(ecid_[a-z0-9\-_]{2,96}|cus_[a-f0-9]{32})$/)
      if principal_id !~ pattern
        fail ArgumentError, "invalid value for \"principal_id\", must conform to the pattern #{pattern}."
      end

      @principal_id = principal_id
    end

    # Custom attribute writer method with validation
    # @param [Object] trust_tier Value to be assigned
    def trust_tier=(trust_tier)
      if trust_tier.nil?
        fail ArgumentError, 'trust_tier cannot be nil'
      end
      if trust_tier > 1.0
        fail ArgumentError, 'invalid value for "trust_tier", must be smaller than or equal to 1.0.'
      end

      if trust_tier < 0.0
        fail ArgumentError, 'invalid value for "trust_tier", must be greater than or equal to 0.0.'
      end

      @trust_tier = trust_tier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          provider == o.provider &&
          model == o.model &&
          principal_id == o.principal_id &&
          trust_tier == o.trust_tier &&
          capabilities == o.capabilities
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [provider, model, principal_id, trust_tier, capabilities].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
