=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.10
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Request for synchronous purchase risk check.
  class CheckRequest < ApiModelBase
    # (optional) event being checked, this may expand later beyond 'purchase'.
    attr_accessor :event_type

    # Server-minted unique payment identifier.
    attr_accessor :payment_intent_id

    attr_accessor :entities

    attr_accessor :purchase

    attr_accessor :identity

    # Optional 3rd party risk assessments (e.g. Shopify, Stripe, Signifyd).
    attr_accessor :external_assessments

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'event_type' => :'eventType',
        :'payment_intent_id' => :'paymentIntentId',
        :'entities' => :'entities',
        :'purchase' => :'purchase',
        :'identity' => :'identity',
        :'external_assessments' => :'externalAssessments'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'event_type' => :'String',
        :'payment_intent_id' => :'String',
        :'entities' => :'EntityIds',
        :'purchase' => :'Purchase',
        :'identity' => :'Identity',
        :'external_assessments' => :'Array<ExternalAssessment>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::CheckRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::CheckRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      else
        self.event_type = 'purchase'
      end

      if attributes.key?(:'payment_intent_id')
        self.payment_intent_id = attributes[:'payment_intent_id']
      end

      if attributes.key?(:'entities')
        self.entities = attributes[:'entities']
      else
        self.entities = nil
      end

      if attributes.key?(:'purchase')
        self.purchase = attributes[:'purchase']
      else
        self.purchase = nil
      end

      if attributes.key?(:'identity')
        self.identity = attributes[:'identity']
      end

      if attributes.key?(:'external_assessments')
        if (value = attributes[:'external_assessments']).is_a?(Array)
          self.external_assessments = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@payment_intent_id.nil? && @payment_intent_id.to_s.length > 35
        invalid_properties.push('invalid value for "payment_intent_id", the character length must be smaller than or equal to 35.')
      end

      if !@payment_intent_id.nil? && @payment_intent_id.to_s.length < 35
        invalid_properties.push('invalid value for "payment_intent_id", the character length must be greater than or equal to 35.')
      end

      pattern = Regexp.new(/^pi_[a-f0-9]{32}$/)
      if !@payment_intent_id.nil? && @payment_intent_id !~ pattern
        invalid_properties.push("invalid value for \"payment_intent_id\", must conform to the pattern #{pattern}.")
      end

      if @entities.nil?
        invalid_properties.push('invalid value for "entities", entities cannot be nil.')
      end

      if @purchase.nil?
        invalid_properties.push('invalid value for "purchase", purchase cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      event_type_validator = EnumAttributeValidator.new('String', ["purchase"])
      return false unless event_type_validator.valid?(@event_type)
      return false if !@payment_intent_id.nil? && @payment_intent_id.to_s.length > 35
      return false if !@payment_intent_id.nil? && @payment_intent_id.to_s.length < 35
      return false if !@payment_intent_id.nil? && @payment_intent_id !~ Regexp.new(/^pi_[a-f0-9]{32}$/)
      return false if @entities.nil?
      return false if @purchase.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] event_type Object to be assigned
    def event_type=(event_type)
      validator = EnumAttributeValidator.new('String', ["purchase"])
      unless validator.valid?(event_type)
        fail ArgumentError, "invalid value for \"event_type\", must be one of #{validator.allowable_values}."
      end
      @event_type = event_type
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_intent_id Value to be assigned
    def payment_intent_id=(payment_intent_id)
      if payment_intent_id.to_s.length > 35
        fail ArgumentError, 'invalid value for "payment_intent_id", the character length must be smaller than or equal to 35.'
      end

      if payment_intent_id.to_s.length < 35
        fail ArgumentError, 'invalid value for "payment_intent_id", the character length must be greater than or equal to 35.'
      end

      pattern = Regexp.new(/^pi_[a-f0-9]{32}$/)
      if payment_intent_id !~ pattern
        fail ArgumentError, "invalid value for \"payment_intent_id\", must conform to the pattern #{pattern}."
      end

      @payment_intent_id = payment_intent_id
    end

    # Custom attribute writer method with validation
    # @param [Object] entities Value to be assigned
    def entities=(entities)
      if entities.nil?
        fail ArgumentError, 'entities cannot be nil'
      end

      @entities = entities
    end

    # Custom attribute writer method with validation
    # @param [Object] purchase Value to be assigned
    def purchase=(purchase)
      if purchase.nil?
        fail ArgumentError, 'purchase cannot be nil'
      end

      @purchase = purchase
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event_type == o.event_type &&
          payment_intent_id == o.payment_intent_id &&
          entities == o.entities &&
          purchase == o.purchase &&
          identity == o.identity &&
          external_assessments == o.external_assessments
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [event_type, payment_intent_id, entities, purchase, identity, external_assessments].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
