=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.1
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # The synchronous risk decision for a purchase.
  class DecisionResponse < ApiModelBase
    # Alogram's unique, authoritative evaluation and transaction identifier. Prefixed with 'pi_' for purchases.
    attr_accessor :id

    # The authoritative, absolute policy command for this transaction. Downstream systems must bind their operational behavior (approve/decline/review) directly to this field.
    attr_accessor :decision

    # RFC 3339 timestamp with timezone.
    attr_accessor :decision_at

    # The authoritative, policy-adjusted blended risk score (0.0 - 1.0) derived from expert fusion.
    attr_accessor :risk_score

    # Structured reason details for the decision.
    attr_accessor :reasons

    attr_accessor :breakdown

    attr_accessor :policy

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'decision' => :'decision',
        :'decision_at' => :'decisionAt',
        :'risk_score' => :'riskScore',
        :'reasons' => :'reasons',
        :'breakdown' => :'breakdown',
        :'policy' => :'policy'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'decision' => :'String',
        :'decision_at' => :'String',
        :'risk_score' => :'Float',
        :'reasons' => :'Array<ReasonDetail>',
        :'breakdown' => :'RiskBreakdown',
        :'policy' => :'DecisionResponsePolicy'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::DecisionResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::DecisionResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'decision')
        self.decision = attributes[:'decision']
      else
        self.decision = nil
      end

      if attributes.key?(:'decision_at')
        self.decision_at = attributes[:'decision_at']
      else
        self.decision_at = nil
      end

      if attributes.key?(:'risk_score')
        self.risk_score = attributes[:'risk_score']
      else
        self.risk_score = nil
      end

      if attributes.key?(:'reasons')
        if (value = attributes[:'reasons']).is_a?(Array)
          self.reasons = value
        end
      end

      if attributes.key?(:'breakdown')
        self.breakdown = attributes[:'breakdown']
      end

      if attributes.key?(:'policy')
        self.policy = attributes[:'policy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @decision.nil?
        invalid_properties.push('invalid value for "decision", decision cannot be nil.')
      end

      if @decision_at.nil?
        invalid_properties.push('invalid value for "decision_at", decision_at cannot be nil.')
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/)
      if @decision_at !~ pattern
        invalid_properties.push("invalid value for \"decision_at\", must conform to the pattern #{pattern}.")
      end

      if @risk_score.nil?
        invalid_properties.push('invalid value for "risk_score", risk_score cannot be nil.')
      end

      if @risk_score > 1.0
        invalid_properties.push('invalid value for "risk_score", must be smaller than or equal to 1.0.')
      end

      if @risk_score < 0.0
        invalid_properties.push('invalid value for "risk_score", must be greater than or equal to 0.0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @decision.nil?
      decision_validator = EnumAttributeValidator.new('String', ["approve", "review", "decline", "step_up"])
      return false unless decision_validator.valid?(@decision)
      return false if @decision_at.nil?
      return false if @decision_at !~ Regexp.new(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/)
      return false if @risk_score.nil?
      return false if @risk_score > 1.0
      return false if @risk_score < 0.0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] decision Object to be assigned
    def decision=(decision)
      validator = EnumAttributeValidator.new('String', ["approve", "review", "decline", "step_up"])
      unless validator.valid?(decision)
        fail ArgumentError, "invalid value for \"decision\", must be one of #{validator.allowable_values}."
      end
      @decision = decision
    end

    # Custom attribute writer method with validation
    # @param [Object] decision_at Value to be assigned
    def decision_at=(decision_at)
      if decision_at.nil?
        fail ArgumentError, 'decision_at cannot be nil'
      end
      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/)
      if decision_at !~ pattern
        fail ArgumentError, "invalid value for \"decision_at\", must conform to the pattern #{pattern}."
      end

      @decision_at = decision_at
    end

    # Custom attribute writer method with validation
    # @param [Object] risk_score Value to be assigned
    def risk_score=(risk_score)
      if risk_score.nil?
        fail ArgumentError, 'risk_score cannot be nil'
      end
      if risk_score > 1.0
        fail ArgumentError, 'invalid value for "risk_score", must be smaller than or equal to 1.0.'
      end

      if risk_score < 0.0
        fail ArgumentError, 'invalid value for "risk_score", must be greater than or equal to 0.0.'
      end

      @risk_score = risk_score
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          decision == o.decision &&
          decision_at == o.decision_at &&
          risk_score == o.risk_score &&
          reasons == o.reasons &&
          breakdown == o.breakdown &&
          policy == o.policy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, decision, decision_at, risk_score, reasons, breakdown, policy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
