=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.23
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  class DecisionResolutionRequest < ApiModelBase
    # The business entity type being resolved.
    attr_accessor :target_type

    # The unique identifier of the target entity under review (e.g. pi_*).
    attr_accessor :target_id

    # The resolution action to apply to the target.
    attr_accessor :decision

    attr_accessor :analyst

    # The ML-feedback ground-truth reason classification.
    attr_accessor :resolution_reason

    # Additional operational notes or reasoning for this resolution.
    attr_accessor :notes

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'target_type' => :'targetType',
        :'target_id' => :'targetId',
        :'decision' => :'decision',
        :'analyst' => :'analyst',
        :'resolution_reason' => :'resolutionReason',
        :'notes' => :'notes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'target_type' => :'String',
        :'target_id' => :'String',
        :'decision' => :'String',
        :'analyst' => :'DecisionResolutionRequestAnalyst',
        :'resolution_reason' => :'String',
        :'notes' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::DecisionResolutionRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::DecisionResolutionRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'target_type')
        self.target_type = attributes[:'target_type']
      else
        self.target_type = nil
      end

      if attributes.key?(:'target_id')
        self.target_id = attributes[:'target_id']
      else
        self.target_id = nil
      end

      if attributes.key?(:'decision')
        self.decision = attributes[:'decision']
      else
        self.decision = nil
      end

      if attributes.key?(:'analyst')
        self.analyst = attributes[:'analyst']
      else
        self.analyst = nil
      end

      if attributes.key?(:'resolution_reason')
        self.resolution_reason = attributes[:'resolution_reason']
      else
        self.resolution_reason = nil
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @target_type.nil?
        invalid_properties.push('invalid value for "target_type", target_type cannot be nil.')
      end

      if @target_id.nil?
        invalid_properties.push('invalid value for "target_id", target_id cannot be nil.')
      end

      if @decision.nil?
        invalid_properties.push('invalid value for "decision", decision cannot be nil.')
      end

      if @analyst.nil?
        invalid_properties.push('invalid value for "analyst", analyst cannot be nil.')
      end

      if @resolution_reason.nil?
        invalid_properties.push('invalid value for "resolution_reason", resolution_reason cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @target_type.nil?
      target_type_validator = EnumAttributeValidator.new('String', ["payment_intent", "account_event", "agent_delegation"])
      return false unless target_type_validator.valid?(@target_type)
      return false if @target_id.nil?
      return false if @decision.nil?
      decision_validator = EnumAttributeValidator.new('String', ["approve", "block", "challenge", "escalate"])
      return false unless decision_validator.valid?(@decision)
      return false if @analyst.nil?
      return false if @resolution_reason.nil?
      resolution_reason_validator = EnumAttributeValidator.new('String', ["legit_human", "legit_agent_authorized", "unauthorized_agent", "card_testing", "account_takeover", "friendly_fraud"])
      return false unless resolution_reason_validator.valid?(@resolution_reason)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] target_type Object to be assigned
    def target_type=(target_type)
      validator = EnumAttributeValidator.new('String', ["payment_intent", "account_event", "agent_delegation"])
      unless validator.valid?(target_type)
        fail ArgumentError, "invalid value for \"target_type\", must be one of #{validator.allowable_values}."
      end
      @target_type = target_type
    end

    # Custom attribute writer method with validation
    # @param [Object] target_id Value to be assigned
    def target_id=(target_id)
      if target_id.nil?
        fail ArgumentError, 'target_id cannot be nil'
      end

      @target_id = target_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] decision Object to be assigned
    def decision=(decision)
      validator = EnumAttributeValidator.new('String', ["approve", "block", "challenge", "escalate"])
      unless validator.valid?(decision)
        fail ArgumentError, "invalid value for \"decision\", must be one of #{validator.allowable_values}."
      end
      @decision = decision
    end

    # Custom attribute writer method with validation
    # @param [Object] analyst Value to be assigned
    def analyst=(analyst)
      if analyst.nil?
        fail ArgumentError, 'analyst cannot be nil'
      end

      @analyst = analyst
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] resolution_reason Object to be assigned
    def resolution_reason=(resolution_reason)
      validator = EnumAttributeValidator.new('String', ["legit_human", "legit_agent_authorized", "unauthorized_agent", "card_testing", "account_takeover", "friendly_fraud"])
      unless validator.valid?(resolution_reason)
        fail ArgumentError, "invalid value for \"resolution_reason\", must be one of #{validator.allowable_values}."
      end
      @resolution_reason = resolution_reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          target_type == o.target_type &&
          target_id == o.target_id &&
          decision == o.decision &&
          analyst == o.analyst &&
          resolution_reason == o.resolution_reason &&
          notes == o.notes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [target_type, target_id, decision, analyst, resolution_reason, notes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
