=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Aggregated device fingerprinting and behavioral patterns used for fraud detection.
  class DeviceInfo < ApiModelBase
    # Unique hash representing the device's fingerprint. Lowercase hex. Prefix \"fp_\". 
    attr_accessor :fingerprint

    # Browser's User-Agent string, useful for identifying OS and browser type.  Must be between 10 and 512 printable ASCII characters. 
    attr_accessor :user_agent

    attr_accessor :ip

    attr_accessor :integrity

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'fingerprint' => :'fingerprint',
        :'user_agent' => :'userAgent',
        :'ip' => :'ip',
        :'integrity' => :'integrity'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'fingerprint' => :'String',
        :'user_agent' => :'String',
        :'ip' => :'IpInfo',
        :'integrity' => :'Integrity'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::DeviceInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::DeviceInfo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'fingerprint')
        self.fingerprint = attributes[:'fingerprint']
      end

      if attributes.key?(:'user_agent')
        self.user_agent = attributes[:'user_agent']
      end

      if attributes.key?(:'ip')
        self.ip = attributes[:'ip']
      end

      if attributes.key?(:'integrity')
        self.integrity = attributes[:'integrity']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@fingerprint.nil? && @fingerprint.to_s.length > 67
        invalid_properties.push('invalid value for "fingerprint", the character length must be smaller than or equal to 67.')
      end

      if !@fingerprint.nil? && @fingerprint.to_s.length < 35
        invalid_properties.push('invalid value for "fingerprint", the character length must be greater than or equal to 35.')
      end

      pattern = Regexp.new(/^fp_[a-f0-9]{32,64}$/)
      if !@fingerprint.nil? && @fingerprint !~ pattern
        invalid_properties.push("invalid value for \"fingerprint\", must conform to the pattern #{pattern}.")
      end

      if !@user_agent.nil? && @user_agent.to_s.length > 512
        invalid_properties.push('invalid value for "user_agent", the character length must be smaller than or equal to 512.')
      end

      if !@user_agent.nil? && @user_agent.to_s.length < 10
        invalid_properties.push('invalid value for "user_agent", the character length must be greater than or equal to 10.')
      end

      pattern = Regexp.new(/^[ -~]{10,512}$/)
      if !@user_agent.nil? && @user_agent !~ pattern
        invalid_properties.push("invalid value for \"user_agent\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@fingerprint.nil? && @fingerprint.to_s.length > 67
      return false if !@fingerprint.nil? && @fingerprint.to_s.length < 35
      return false if !@fingerprint.nil? && @fingerprint !~ Regexp.new(/^fp_[a-f0-9]{32,64}$/)
      return false if !@user_agent.nil? && @user_agent.to_s.length > 512
      return false if !@user_agent.nil? && @user_agent.to_s.length < 10
      return false if !@user_agent.nil? && @user_agent !~ Regexp.new(/^[ -~]{10,512}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] fingerprint Value to be assigned
    def fingerprint=(fingerprint)
      if fingerprint.nil?
        fail ArgumentError, 'fingerprint cannot be nil'
      end

      if fingerprint.to_s.length > 67
        fail ArgumentError, 'invalid value for "fingerprint", the character length must be smaller than or equal to 67.'
      end

      if fingerprint.to_s.length < 35
        fail ArgumentError, 'invalid value for "fingerprint", the character length must be greater than or equal to 35.'
      end

      pattern = Regexp.new(/^fp_[a-f0-9]{32,64}$/)
      if fingerprint !~ pattern
        fail ArgumentError, "invalid value for \"fingerprint\", must conform to the pattern #{pattern}."
      end

      @fingerprint = fingerprint
    end

    # Custom attribute writer method with validation
    # @param [Object] user_agent Value to be assigned
    def user_agent=(user_agent)
      if user_agent.nil?
        fail ArgumentError, 'user_agent cannot be nil'
      end

      if user_agent.to_s.length > 512
        fail ArgumentError, 'invalid value for "user_agent", the character length must be smaller than or equal to 512.'
      end

      if user_agent.to_s.length < 10
        fail ArgumentError, 'invalid value for "user_agent", the character length must be greater than or equal to 10.'
      end

      pattern = Regexp.new(/^[ -~]{10,512}$/)
      if user_agent !~ pattern
        fail ArgumentError, "invalid value for \"user_agent\", must conform to the pattern #{pattern}."
      end

      @user_agent = user_agent
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fingerprint == o.fingerprint &&
          user_agent == o.user_agent &&
          ip == o.ip &&
          integrity == o.integrity
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [fingerprint, user_agent, ip, integrity].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
