=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.21
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Canonical entity identifiers (tenant/client/user/device/session). Do not send raw PII. Hash emails/phones/addresses as sha256 and prefix with 'sha256_'. Tiered support:   - tenantId is the top-level SaaS customer (required for all flows).   - clientId is the tenant's downstream business customer (e.g. merchant/partner) and MAY be omitted for     processor / bank / PSP-style integrations.   - endCustomerId is the tenant/client's consumer or business account (cardholder, shopper, etc.) and     MAY be omitted for purely device- or instrument-level checks. 
  class EntityIds < ApiModelBase
    # Canonical ID for the paying organization (Tenant). Opaque, immutable, lowercase.  Must start with \"tid_\" (Legacy) or \"ten_\" (Preferred). 
    attr_accessor :tenant_id

    # Canonical ID for the Tenant’s business customer (e.g., merchant/partner).  Opaque, immutable, lowercase. Must start with \"cid_\" (Legacy) or \"cli_\" (Preferred). 
    attr_accessor :client_id

    # Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Supports \"ecid_\" slugs (Legacy) or \"cus_\" hex (Preferred). 
    attr_accessor :end_customer_id

    # Canonical ID for a Tenant Operator (staff/automation) holding membership in the platform.  Opaque, immutable, lowercase. Supports \"mid_\" slugs (Legacy) or \"op_\" hex (Preferred). 
    attr_accessor :operator_id

    attr_accessor :auth

    # Canonical ID for a marketplace product edition or billing SKU.  Always follows the Fortress-36 (sku_ + 32 hex) format. 
    attr_accessor :sku_id

    # Human-readable identifier for a SKU, used for logic and feature checks. 
    attr_accessor :sku_handle

    # Tokenized instrument ID (non-PCI).
    attr_accessor :payment_instrument_id

    # Server-issued stable device token (device-level identifier). Should persist across sessions and logins on the same browser/device. 
    attr_accessor :device_id

    # Application/user session identifier (login or checkout session). Typically rotates more frequently than deviceId and may be tied to authentication. 
    attr_accessor :session_id

    attr_accessor :agent

    # Normalized+lowercased email hash (e.g., sha256).
    attr_accessor :email_hash

    # Normalized+lowercased email *domain* hash (e.g., sha256).
    attr_accessor :email_domain_hash

    # Normalized+lowercased phone hash (e.g., sha256).
    attr_accessor :phone_hash

    # Normalized+lowercased shipping address hash (e.g., sha256).
    attr_accessor :shipping_address_hash

    # Normalized+lowercased billing address hash (e.g., sha256).
    attr_accessor :billing_address_hash

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tenant_id' => :'tenantId',
        :'client_id' => :'clientId',
        :'end_customer_id' => :'endCustomerId',
        :'operator_id' => :'operatorId',
        :'auth' => :'auth',
        :'sku_id' => :'skuId',
        :'sku_handle' => :'skuHandle',
        :'payment_instrument_id' => :'paymentInstrumentId',
        :'device_id' => :'deviceId',
        :'session_id' => :'sessionId',
        :'agent' => :'agent',
        :'email_hash' => :'emailHash',
        :'email_domain_hash' => :'emailDomainHash',
        :'phone_hash' => :'phoneHash',
        :'shipping_address_hash' => :'shippingAddressHash',
        :'billing_address_hash' => :'billingAddressHash'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tenant_id' => :'String',
        :'client_id' => :'String',
        :'end_customer_id' => :'String',
        :'operator_id' => :'String',
        :'auth' => :'AuthContext',
        :'sku_id' => :'String',
        :'sku_handle' => :'String',
        :'payment_instrument_id' => :'String',
        :'device_id' => :'String',
        :'session_id' => :'String',
        :'agent' => :'AgentManifest',
        :'email_hash' => :'String',
        :'email_domain_hash' => :'String',
        :'phone_hash' => :'String',
        :'shipping_address_hash' => :'String',
        :'billing_address_hash' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::EntityIds` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::EntityIds`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      end

      if attributes.key?(:'client_id')
        self.client_id = attributes[:'client_id']
      end

      if attributes.key?(:'end_customer_id')
        self.end_customer_id = attributes[:'end_customer_id']
      end

      if attributes.key?(:'operator_id')
        self.operator_id = attributes[:'operator_id']
      end

      if attributes.key?(:'auth')
        self.auth = attributes[:'auth']
      end

      if attributes.key?(:'sku_id')
        self.sku_id = attributes[:'sku_id']
      end

      if attributes.key?(:'sku_handle')
        self.sku_handle = attributes[:'sku_handle']
      end

      if attributes.key?(:'payment_instrument_id')
        self.payment_instrument_id = attributes[:'payment_instrument_id']
      end

      if attributes.key?(:'device_id')
        self.device_id = attributes[:'device_id']
      end

      if attributes.key?(:'session_id')
        self.session_id = attributes[:'session_id']
      end

      if attributes.key?(:'agent')
        self.agent = attributes[:'agent']
      end

      if attributes.key?(:'email_hash')
        self.email_hash = attributes[:'email_hash']
      end

      if attributes.key?(:'email_domain_hash')
        self.email_domain_hash = attributes[:'email_domain_hash']
      end

      if attributes.key?(:'phone_hash')
        self.phone_hash = attributes[:'phone_hash']
      end

      if attributes.key?(:'shipping_address_hash')
        self.shipping_address_hash = attributes[:'shipping_address_hash']
      end

      if attributes.key?(:'billing_address_hash')
        self.billing_address_hash = attributes[:'billing_address_hash']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@tenant_id.nil? && @tenant_id.to_s.length > 68
        invalid_properties.push('invalid value for "tenant_id", the character length must be smaller than or equal to 68.')
      end

      if !@tenant_id.nil? && @tenant_id.to_s.length < 6
        invalid_properties.push('invalid value for "tenant_id", the character length must be greater than or equal to 6.')
      end

      pattern = Regexp.new(/^(tid|ten)_[a-z0-9_-]{2,64}$/)
      if !@tenant_id.nil? && @tenant_id !~ pattern
        invalid_properties.push("invalid value for \"tenant_id\", must conform to the pattern #{pattern}.")
      end

      if !@client_id.nil? && @client_id.to_s.length > 100
        invalid_properties.push('invalid value for "client_id", the character length must be smaller than or equal to 100.')
      end

      if !@client_id.nil? && @client_id.to_s.length < 6
        invalid_properties.push('invalid value for "client_id", the character length must be greater than or equal to 6.')
      end

      pattern = Regexp.new(/^(cid|cli)_[a-z0-9_-]{2,96}$/)
      if !@client_id.nil? && @client_id !~ pattern
        invalid_properties.push("invalid value for \"client_id\", must conform to the pattern #{pattern}.")
      end

      if !@end_customer_id.nil? && @end_customer_id.to_s.length > 100
        invalid_properties.push('invalid value for "end_customer_id", the character length must be smaller than or equal to 100.')
      end

      if !@end_customer_id.nil? && @end_customer_id.to_s.length < 6
        invalid_properties.push('invalid value for "end_customer_id", the character length must be greater than or equal to 6.')
      end

      pattern = Regexp.new(/^(ecid_[a-z0-9\-_]{2,96}|cus_[a-f0-9]{32})$/)
      if !@end_customer_id.nil? && @end_customer_id !~ pattern
        invalid_properties.push("invalid value for \"end_customer_id\", must conform to the pattern #{pattern}.")
      end

      if !@operator_id.nil? && @operator_id.to_s.length > 100
        invalid_properties.push('invalid value for "operator_id", the character length must be smaller than or equal to 100.')
      end

      if !@operator_id.nil? && @operator_id.to_s.length < 5
        invalid_properties.push('invalid value for "operator_id", the character length must be greater than or equal to 5.')
      end

      pattern = Regexp.new(/^(mid_[a-z0-9_-]{2,96}|op_[a-f0-9]{32})$/)
      if !@operator_id.nil? && @operator_id !~ pattern
        invalid_properties.push("invalid value for \"operator_id\", must conform to the pattern #{pattern}.")
      end

      if !@sku_id.nil? && @sku_id.to_s.length > 37
        invalid_properties.push('invalid value for "sku_id", the character length must be smaller than or equal to 37.')
      end

      if !@sku_id.nil? && @sku_id.to_s.length < 36
        invalid_properties.push('invalid value for "sku_id", the character length must be greater than or equal to 36.')
      end

      pattern = Regexp.new(/^sku_[a-f0-9]{32}$/)
      if !@sku_id.nil? && @sku_id !~ pattern
        invalid_properties.push("invalid value for \"sku_id\", must conform to the pattern #{pattern}.")
      end

      if !@sku_handle.nil? && @sku_handle.to_s.length > 64
        invalid_properties.push('invalid value for "sku_handle", the character length must be smaller than or equal to 64.')
      end

      if !@sku_handle.nil? && @sku_handle.to_s.length < 2
        invalid_properties.push('invalid value for "sku_handle", the character length must be greater than or equal to 2.')
      end

      pattern = Regexp.new(/^[a-z0-9\-_]{2,64}$/)
      if !@sku_handle.nil? && @sku_handle !~ pattern
        invalid_properties.push("invalid value for \"sku_handle\", must conform to the pattern #{pattern}.")
      end

      if !@payment_instrument_id.nil? && @payment_instrument_id.to_s.length > 100
        invalid_properties.push('invalid value for "payment_instrument_id", the character length must be smaller than or equal to 100.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9\-_:]{2,96}$/)
      if !@payment_instrument_id.nil? && @payment_instrument_id !~ pattern
        invalid_properties.push("invalid value for \"payment_instrument_id\", must conform to the pattern #{pattern}.")
      end

      if !@device_id.nil? && @device_id.to_s.length > 100
        invalid_properties.push('invalid value for "device_id", the character length must be smaller than or equal to 100.')
      end

      pattern = Regexp.new(/^did_[a-zA-Z0-9\-_:]{2,96}$/)
      if !@device_id.nil? && @device_id !~ pattern
        invalid_properties.push("invalid value for \"device_id\", must conform to the pattern #{pattern}.")
      end

      if !@session_id.nil? && @session_id.to_s.length > 100
        invalid_properties.push('invalid value for "session_id", the character length must be smaller than or equal to 100.')
      end

      pattern = Regexp.new(/^sid_[a-zA-Z0-9\-_:]{2,96}$/)
      if !@session_id.nil? && @session_id !~ pattern
        invalid_properties.push("invalid value for \"session_id\", must conform to the pattern #{pattern}.")
      end

      if !@email_hash.nil? && @email_hash.to_s.length > 71
        invalid_properties.push('invalid value for "email_hash", the character length must be smaller than or equal to 71.')
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if !@email_hash.nil? && @email_hash !~ pattern
        invalid_properties.push("invalid value for \"email_hash\", must conform to the pattern #{pattern}.")
      end

      if !@email_domain_hash.nil? && @email_domain_hash.to_s.length > 71
        invalid_properties.push('invalid value for "email_domain_hash", the character length must be smaller than or equal to 71.')
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if !@email_domain_hash.nil? && @email_domain_hash !~ pattern
        invalid_properties.push("invalid value for \"email_domain_hash\", must conform to the pattern #{pattern}.")
      end

      if !@phone_hash.nil? && @phone_hash.to_s.length > 71
        invalid_properties.push('invalid value for "phone_hash", the character length must be smaller than or equal to 71.')
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if !@phone_hash.nil? && @phone_hash !~ pattern
        invalid_properties.push("invalid value for \"phone_hash\", must conform to the pattern #{pattern}.")
      end

      if !@shipping_address_hash.nil? && @shipping_address_hash.to_s.length > 71
        invalid_properties.push('invalid value for "shipping_address_hash", the character length must be smaller than or equal to 71.')
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if !@shipping_address_hash.nil? && @shipping_address_hash !~ pattern
        invalid_properties.push("invalid value for \"shipping_address_hash\", must conform to the pattern #{pattern}.")
      end

      if !@billing_address_hash.nil? && @billing_address_hash.to_s.length > 71
        invalid_properties.push('invalid value for "billing_address_hash", the character length must be smaller than or equal to 71.')
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if !@billing_address_hash.nil? && @billing_address_hash !~ pattern
        invalid_properties.push("invalid value for \"billing_address_hash\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@tenant_id.nil? && @tenant_id.to_s.length > 68
      return false if !@tenant_id.nil? && @tenant_id.to_s.length < 6
      return false if !@tenant_id.nil? && @tenant_id !~ Regexp.new(/^(tid|ten)_[a-z0-9_-]{2,64}$/)
      return false if !@client_id.nil? && @client_id.to_s.length > 100
      return false if !@client_id.nil? && @client_id.to_s.length < 6
      return false if !@client_id.nil? && @client_id !~ Regexp.new(/^(cid|cli)_[a-z0-9_-]{2,96}$/)
      return false if !@end_customer_id.nil? && @end_customer_id.to_s.length > 100
      return false if !@end_customer_id.nil? && @end_customer_id.to_s.length < 6
      return false if !@end_customer_id.nil? && @end_customer_id !~ Regexp.new(/^(ecid_[a-z0-9\-_]{2,96}|cus_[a-f0-9]{32})$/)
      return false if !@operator_id.nil? && @operator_id.to_s.length > 100
      return false if !@operator_id.nil? && @operator_id.to_s.length < 5
      return false if !@operator_id.nil? && @operator_id !~ Regexp.new(/^(mid_[a-z0-9_-]{2,96}|op_[a-f0-9]{32})$/)
      return false if !@sku_id.nil? && @sku_id.to_s.length > 37
      return false if !@sku_id.nil? && @sku_id.to_s.length < 36
      return false if !@sku_id.nil? && @sku_id !~ Regexp.new(/^sku_[a-f0-9]{32}$/)
      return false if !@sku_handle.nil? && @sku_handle.to_s.length > 64
      return false if !@sku_handle.nil? && @sku_handle.to_s.length < 2
      return false if !@sku_handle.nil? && @sku_handle !~ Regexp.new(/^[a-z0-9\-_]{2,64}$/)
      return false if !@payment_instrument_id.nil? && @payment_instrument_id.to_s.length > 100
      return false if !@payment_instrument_id.nil? && @payment_instrument_id !~ Regexp.new(/^[a-zA-Z0-9\-_:]{2,96}$/)
      return false if !@device_id.nil? && @device_id.to_s.length > 100
      return false if !@device_id.nil? && @device_id !~ Regexp.new(/^did_[a-zA-Z0-9\-_:]{2,96}$/)
      return false if !@session_id.nil? && @session_id.to_s.length > 100
      return false if !@session_id.nil? && @session_id !~ Regexp.new(/^sid_[a-zA-Z0-9\-_:]{2,96}$/)
      return false if !@email_hash.nil? && @email_hash.to_s.length > 71
      return false if !@email_hash.nil? && @email_hash !~ Regexp.new(/^sha256_[0-9a-f]{64}$/)
      return false if !@email_domain_hash.nil? && @email_domain_hash.to_s.length > 71
      return false if !@email_domain_hash.nil? && @email_domain_hash !~ Regexp.new(/^sha256_[0-9a-f]{64}$/)
      return false if !@phone_hash.nil? && @phone_hash.to_s.length > 71
      return false if !@phone_hash.nil? && @phone_hash !~ Regexp.new(/^sha256_[0-9a-f]{64}$/)
      return false if !@shipping_address_hash.nil? && @shipping_address_hash.to_s.length > 71
      return false if !@shipping_address_hash.nil? && @shipping_address_hash !~ Regexp.new(/^sha256_[0-9a-f]{64}$/)
      return false if !@billing_address_hash.nil? && @billing_address_hash.to_s.length > 71
      return false if !@billing_address_hash.nil? && @billing_address_hash !~ Regexp.new(/^sha256_[0-9a-f]{64}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.to_s.length > 68
        fail ArgumentError, 'invalid value for "tenant_id", the character length must be smaller than or equal to 68.'
      end

      if tenant_id.to_s.length < 6
        fail ArgumentError, 'invalid value for "tenant_id", the character length must be greater than or equal to 6.'
      end

      pattern = Regexp.new(/^(tid|ten)_[a-z0-9_-]{2,64}$/)
      if tenant_id !~ pattern
        fail ArgumentError, "invalid value for \"tenant_id\", must conform to the pattern #{pattern}."
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] client_id Value to be assigned
    def client_id=(client_id)
      if client_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "client_id", the character length must be smaller than or equal to 100.'
      end

      if client_id.to_s.length < 6
        fail ArgumentError, 'invalid value for "client_id", the character length must be greater than or equal to 6.'
      end

      pattern = Regexp.new(/^(cid|cli)_[a-z0-9_-]{2,96}$/)
      if client_id !~ pattern
        fail ArgumentError, "invalid value for \"client_id\", must conform to the pattern #{pattern}."
      end

      @client_id = client_id
    end

    # Custom attribute writer method with validation
    # @param [Object] end_customer_id Value to be assigned
    def end_customer_id=(end_customer_id)
      if end_customer_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "end_customer_id", the character length must be smaller than or equal to 100.'
      end

      if end_customer_id.to_s.length < 6
        fail ArgumentError, 'invalid value for "end_customer_id", the character length must be greater than or equal to 6.'
      end

      pattern = Regexp.new(/^(ecid_[a-z0-9\-_]{2,96}|cus_[a-f0-9]{32})$/)
      if end_customer_id !~ pattern
        fail ArgumentError, "invalid value for \"end_customer_id\", must conform to the pattern #{pattern}."
      end

      @end_customer_id = end_customer_id
    end

    # Custom attribute writer method with validation
    # @param [Object] operator_id Value to be assigned
    def operator_id=(operator_id)
      if operator_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "operator_id", the character length must be smaller than or equal to 100.'
      end

      if operator_id.to_s.length < 5
        fail ArgumentError, 'invalid value for "operator_id", the character length must be greater than or equal to 5.'
      end

      pattern = Regexp.new(/^(mid_[a-z0-9_-]{2,96}|op_[a-f0-9]{32})$/)
      if operator_id !~ pattern
        fail ArgumentError, "invalid value for \"operator_id\", must conform to the pattern #{pattern}."
      end

      @operator_id = operator_id
    end

    # Custom attribute writer method with validation
    # @param [Object] sku_id Value to be assigned
    def sku_id=(sku_id)
      if sku_id.to_s.length > 37
        fail ArgumentError, 'invalid value for "sku_id", the character length must be smaller than or equal to 37.'
      end

      if sku_id.to_s.length < 36
        fail ArgumentError, 'invalid value for "sku_id", the character length must be greater than or equal to 36.'
      end

      pattern = Regexp.new(/^sku_[a-f0-9]{32}$/)
      if sku_id !~ pattern
        fail ArgumentError, "invalid value for \"sku_id\", must conform to the pattern #{pattern}."
      end

      @sku_id = sku_id
    end

    # Custom attribute writer method with validation
    # @param [Object] sku_handle Value to be assigned
    def sku_handle=(sku_handle)
      if sku_handle.to_s.length > 64
        fail ArgumentError, 'invalid value for "sku_handle", the character length must be smaller than or equal to 64.'
      end

      if sku_handle.to_s.length < 2
        fail ArgumentError, 'invalid value for "sku_handle", the character length must be greater than or equal to 2.'
      end

      pattern = Regexp.new(/^[a-z0-9\-_]{2,64}$/)
      if sku_handle !~ pattern
        fail ArgumentError, "invalid value for \"sku_handle\", must conform to the pattern #{pattern}."
      end

      @sku_handle = sku_handle
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_instrument_id Value to be assigned
    def payment_instrument_id=(payment_instrument_id)
      if payment_instrument_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "payment_instrument_id", the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9\-_:]{2,96}$/)
      if payment_instrument_id !~ pattern
        fail ArgumentError, "invalid value for \"payment_instrument_id\", must conform to the pattern #{pattern}."
      end

      @payment_instrument_id = payment_instrument_id
    end

    # Custom attribute writer method with validation
    # @param [Object] device_id Value to be assigned
    def device_id=(device_id)
      if device_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "device_id", the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/^did_[a-zA-Z0-9\-_:]{2,96}$/)
      if device_id !~ pattern
        fail ArgumentError, "invalid value for \"device_id\", must conform to the pattern #{pattern}."
      end

      @device_id = device_id
    end

    # Custom attribute writer method with validation
    # @param [Object] session_id Value to be assigned
    def session_id=(session_id)
      if session_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "session_id", the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/^sid_[a-zA-Z0-9\-_:]{2,96}$/)
      if session_id !~ pattern
        fail ArgumentError, "invalid value for \"session_id\", must conform to the pattern #{pattern}."
      end

      @session_id = session_id
    end

    # Custom attribute writer method with validation
    # @param [Object] email_hash Value to be assigned
    def email_hash=(email_hash)
      if email_hash.to_s.length > 71
        fail ArgumentError, 'invalid value for "email_hash", the character length must be smaller than or equal to 71.'
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if email_hash !~ pattern
        fail ArgumentError, "invalid value for \"email_hash\", must conform to the pattern #{pattern}."
      end

      @email_hash = email_hash
    end

    # Custom attribute writer method with validation
    # @param [Object] email_domain_hash Value to be assigned
    def email_domain_hash=(email_domain_hash)
      if email_domain_hash.to_s.length > 71
        fail ArgumentError, 'invalid value for "email_domain_hash", the character length must be smaller than or equal to 71.'
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if email_domain_hash !~ pattern
        fail ArgumentError, "invalid value for \"email_domain_hash\", must conform to the pattern #{pattern}."
      end

      @email_domain_hash = email_domain_hash
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_hash Value to be assigned
    def phone_hash=(phone_hash)
      if phone_hash.to_s.length > 71
        fail ArgumentError, 'invalid value for "phone_hash", the character length must be smaller than or equal to 71.'
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if phone_hash !~ pattern
        fail ArgumentError, "invalid value for \"phone_hash\", must conform to the pattern #{pattern}."
      end

      @phone_hash = phone_hash
    end

    # Custom attribute writer method with validation
    # @param [Object] shipping_address_hash Value to be assigned
    def shipping_address_hash=(shipping_address_hash)
      if shipping_address_hash.to_s.length > 71
        fail ArgumentError, 'invalid value for "shipping_address_hash", the character length must be smaller than or equal to 71.'
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if shipping_address_hash !~ pattern
        fail ArgumentError, "invalid value for \"shipping_address_hash\", must conform to the pattern #{pattern}."
      end

      @shipping_address_hash = shipping_address_hash
    end

    # Custom attribute writer method with validation
    # @param [Object] billing_address_hash Value to be assigned
    def billing_address_hash=(billing_address_hash)
      if billing_address_hash.to_s.length > 71
        fail ArgumentError, 'invalid value for "billing_address_hash", the character length must be smaller than or equal to 71.'
      end

      pattern = Regexp.new(/^sha256_[0-9a-f]{64}$/)
      if billing_address_hash !~ pattern
        fail ArgumentError, "invalid value for \"billing_address_hash\", must conform to the pattern #{pattern}."
      end

      @billing_address_hash = billing_address_hash
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tenant_id == o.tenant_id &&
          client_id == o.client_id &&
          end_customer_id == o.end_customer_id &&
          operator_id == o.operator_id &&
          auth == o.auth &&
          sku_id == o.sku_id &&
          sku_handle == o.sku_handle &&
          payment_instrument_id == o.payment_instrument_id &&
          device_id == o.device_id &&
          session_id == o.session_id &&
          agent == o.agent &&
          email_hash == o.email_hash &&
          email_domain_hash == o.email_domain_hash &&
          phone_hash == o.phone_hash &&
          shipping_address_hash == o.shipping_address_hash &&
          billing_address_hash == o.billing_address_hash
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tenant_id, client_id, end_customer_id, operator_id, auth, sku_id, sku_handle, payment_instrument_id, device_id, session_id, agent, email_hash, email_domain_hash, phone_hash, shipping_address_hash, billing_address_hash].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
