=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.2
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Optional raw identity details for the account associated with the purchase. These fields (email, phone, addresses) are used for normalization, hashing, and risk feature extraction (e.g., email/phone/domain scoring, address risk), and are not stored in raw form by Alogram.  When provided, Alogram will derive and/or cross-check: - emailHash / phoneHash / shippingAddressHash / billingAddressHash   in the Alogram entity model - email/phone/domain risk signals - address consistency and geo-distance checks 
  class Identity < ApiModelBase
    # Email address of the customer.
    attr_accessor :email

    # Email domain only (no local part). Useful for domain-level risk and allow/deny lists without sending full email PII. Example: \"gmail.com\", \"merchant-example.co.uk\" 
    attr_accessor :email_domain

    # Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\" 
    attr_accessor :phone

    attr_accessor :shipping_address

    attr_accessor :billing_address

    # Optional: Set to true if client-side bot detection (e.g. reCAPTCHA) triggered.
    attr_accessor :is_bot

    # Optional: Client-side assessment of email reputation.
    attr_accessor :email_reputation

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email' => :'email',
        :'email_domain' => :'emailDomain',
        :'phone' => :'phone',
        :'shipping_address' => :'shippingAddress',
        :'billing_address' => :'billingAddress',
        :'is_bot' => :'isBot',
        :'email_reputation' => :'emailReputation'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'email' => :'String',
        :'email_domain' => :'String',
        :'phone' => :'String',
        :'shipping_address' => :'PostalAddress',
        :'billing_address' => :'PostalAddress',
        :'is_bot' => :'Boolean',
        :'email_reputation' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::Identity` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::Identity`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'email_domain')
        self.email_domain = attributes[:'email_domain']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'shipping_address')
        self.shipping_address = attributes[:'shipping_address']
      end

      if attributes.key?(:'billing_address')
        self.billing_address = attributes[:'billing_address']
      end

      if attributes.key?(:'is_bot')
        self.is_bot = attributes[:'is_bot']
      end

      if attributes.key?(:'email_reputation')
        self.email_reputation = attributes[:'email_reputation']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@email.nil? && @email.to_s.length > 320
        invalid_properties.push('invalid value for "email", the character length must be smaller than or equal to 320.')
      end

      if !@email.nil? && @email.to_s.length < 3
        invalid_properties.push('invalid value for "email", the character length must be greater than or equal to 3.')
      end

      if !@email_domain.nil? && @email_domain.to_s.length > 255
        invalid_properties.push('invalid value for "email_domain", the character length must be smaller than or equal to 255.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/)
      if !@email_domain.nil? && @email_domain !~ pattern
        invalid_properties.push("invalid value for \"email_domain\", must conform to the pattern #{pattern}.")
      end

      if !@phone.nil? && @phone.to_s.length > 30
        invalid_properties.push('invalid value for "phone", the character length must be smaller than or equal to 30.')
      end

      if !@phone.nil? && @phone.to_s.length < 7
        invalid_properties.push('invalid value for "phone", the character length must be greater than or equal to 7.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@email.nil? && @email.to_s.length > 320
      return false if !@email.nil? && @email.to_s.length < 3
      return false if !@email_domain.nil? && @email_domain.to_s.length > 255
      return false if !@email_domain.nil? && @email_domain !~ Regexp.new(/^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/)
      return false if !@phone.nil? && @phone.to_s.length > 30
      return false if !@phone.nil? && @phone.to_s.length < 7
      email_reputation_validator = EnumAttributeValidator.new('String', ["low", "medium", "high"])
      return false unless email_reputation_validator.valid?(@email_reputation)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.to_s.length > 320
        fail ArgumentError, 'invalid value for "email", the character length must be smaller than or equal to 320.'
      end

      if email.to_s.length < 3
        fail ArgumentError, 'invalid value for "email", the character length must be greater than or equal to 3.'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] email_domain Value to be assigned
    def email_domain=(email_domain)
      if email_domain.to_s.length > 255
        fail ArgumentError, 'invalid value for "email_domain", the character length must be smaller than or equal to 255.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/)
      if email_domain !~ pattern
        fail ArgumentError, "invalid value for \"email_domain\", must conform to the pattern #{pattern}."
      end

      @email_domain = email_domain
    end

    # Custom attribute writer method with validation
    # @param [Object] phone Value to be assigned
    def phone=(phone)
      if phone.to_s.length > 30
        fail ArgumentError, 'invalid value for "phone", the character length must be smaller than or equal to 30.'
      end

      if phone.to_s.length < 7
        fail ArgumentError, 'invalid value for "phone", the character length must be greater than or equal to 7.'
      end

      @phone = phone
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] email_reputation Object to be assigned
    def email_reputation=(email_reputation)
      validator = EnumAttributeValidator.new('String', ["low", "medium", "high"])
      unless validator.valid?(email_reputation)
        fail ArgumentError, "invalid value for \"email_reputation\", must be one of #{validator.allowable_values}."
      end
      @email_reputation = email_reputation
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email == o.email &&
          email_domain == o.email_domain &&
          phone == o.phone &&
          shipping_address == o.shipping_address &&
          billing_address == o.billing_address &&
          is_bot == o.is_bot &&
          email_reputation == o.email_reputation
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [email, email_domain, phone, shipping_address, billing_address, is_bot, email_reputation].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
