=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.10
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # The application-layer Interaction object.
  class Interaction < ApiModelBase
    # Unique identifier for the location where the transaction occurred.
    attr_accessor :location_id

    attr_accessor :device_info

    # RFC 3339 timestamp with timezone.
    attr_accessor :timestamp

    attr_accessor :interaction_type

    # Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
    attr_accessor :metadata

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'location_id' => :'locationId',
        :'device_info' => :'deviceInfo',
        :'timestamp' => :'timestamp',
        :'interaction_type' => :'interactionType',
        :'metadata' => :'metadata'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'location_id' => :'String',
        :'device_info' => :'DeviceInfo',
        :'timestamp' => :'String',
        :'interaction_type' => :'InteractionTypeEnum',
        :'metadata' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::Interaction` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::Interaction`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'location_id')
        self.location_id = attributes[:'location_id']
      end

      if attributes.key?(:'device_info')
        self.device_info = attributes[:'device_info']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.key?(:'interaction_type')
        self.interaction_type = attributes[:'interaction_type']
      else
        self.interaction_type = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@location_id.nil? && @location_id.to_s.length > 50
        invalid_properties.push('invalid value for "location_id", the character length must be smaller than or equal to 50.')
      end

      if !@location_id.nil? && @location_id.to_s.length < 3
        invalid_properties.push('invalid value for "location_id", the character length must be greater than or equal to 3.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9\-_]{3,50}$/)
      if !@location_id.nil? && @location_id !~ pattern
        invalid_properties.push("invalid value for \"location_id\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/)
      if !@timestamp.nil? && @timestamp !~ pattern
        invalid_properties.push("invalid value for \"timestamp\", must conform to the pattern #{pattern}.")
      end

      if @interaction_type.nil?
        invalid_properties.push('invalid value for "interaction_type", interaction_type cannot be nil.')
      end

      if !@metadata.nil? && @metadata.to_s.length > 2048
        invalid_properties.push('invalid value for "metadata", the character length must be smaller than or equal to 2048.')
      end

      if !@metadata.nil? && @metadata.to_s.length < 1
        invalid_properties.push('invalid value for "metadata", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@location_id.nil? && @location_id.to_s.length > 50
      return false if !@location_id.nil? && @location_id.to_s.length < 3
      return false if !@location_id.nil? && @location_id !~ Regexp.new(/^[a-zA-Z0-9\-_]{3,50}$/)
      return false if !@timestamp.nil? && @timestamp !~ Regexp.new(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/)
      return false if @interaction_type.nil?
      return false if !@metadata.nil? && @metadata.to_s.length > 2048
      return false if !@metadata.nil? && @metadata.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] location_id Value to be assigned
    def location_id=(location_id)
      if location_id.to_s.length > 50
        fail ArgumentError, 'invalid value for "location_id", the character length must be smaller than or equal to 50.'
      end

      if location_id.to_s.length < 3
        fail ArgumentError, 'invalid value for "location_id", the character length must be greater than or equal to 3.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9\-_]{3,50}$/)
      if location_id !~ pattern
        fail ArgumentError, "invalid value for \"location_id\", must conform to the pattern #{pattern}."
      end

      @location_id = location_id
    end

    # Custom attribute writer method with validation
    # @param [Object] timestamp Value to be assigned
    def timestamp=(timestamp)
      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/)
      if timestamp !~ pattern
        fail ArgumentError, "invalid value for \"timestamp\", must conform to the pattern #{pattern}."
      end

      @timestamp = timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] interaction_type Value to be assigned
    def interaction_type=(interaction_type)
      if interaction_type.nil?
        fail ArgumentError, 'interaction_type cannot be nil'
      end

      @interaction_type = interaction_type
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.to_s.length > 2048
        fail ArgumentError, 'invalid value for "metadata", the character length must be smaller than or equal to 2048.'
      end

      if metadata.to_s.length < 1
        fail ArgumentError, 'invalid value for "metadata", the character length must be greater than or equal to 1.'
      end

      @metadata = metadata
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          location_id == o.location_id &&
          device_info == o.device_info &&
          timestamp == o.timestamp &&
          interaction_type == o.interaction_type &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [location_id, device_info, timestamp, interaction_type, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
