=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.21
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  class IpInfo < ApiModelBase
    # IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255. 
    attr_accessor :ip_address

    # IPv6 address.
    attr_accessor :ipv6

    # IP protocol version.
    attr_accessor :ip_version

    # CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48
    attr_accessor :ip_prefix

    # Autonomous System Number (ASN) of the IP address.
    attr_accessor :asn

    # Organization associated with the IP address.
    attr_accessor :org

    # Company associated with the IP address.
    attr_accessor :company

    # ISO 3166-1 alpha-2 country code.
    attr_accessor :country

    # Region associated with the IP address.
    attr_accessor :region

    # City associated with the IP address.
    attr_accessor :city

    # Postal code associated with the IP address.
    attr_accessor :postal_code

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ip_address' => :'ipAddress',
        :'ipv6' => :'ipv6',
        :'ip_version' => :'ipVersion',
        :'ip_prefix' => :'ipPrefix',
        :'asn' => :'asn',
        :'org' => :'org',
        :'company' => :'company',
        :'country' => :'country',
        :'region' => :'region',
        :'city' => :'city',
        :'postal_code' => :'postalCode'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ip_address' => :'String',
        :'ipv6' => :'String',
        :'ip_version' => :'String',
        :'ip_prefix' => :'String',
        :'asn' => :'String',
        :'org' => :'String',
        :'company' => :'String',
        :'country' => :'String',
        :'region' => :'String',
        :'city' => :'String',
        :'postal_code' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::IpInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::IpInfo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ip_address')
        self.ip_address = attributes[:'ip_address']
      end

      if attributes.key?(:'ipv6')
        self.ipv6 = attributes[:'ipv6']
      end

      if attributes.key?(:'ip_version')
        self.ip_version = attributes[:'ip_version']
      else
        self.ip_version = 'ipv4'
      end

      if attributes.key?(:'ip_prefix')
        self.ip_prefix = attributes[:'ip_prefix']
      end

      if attributes.key?(:'asn')
        self.asn = attributes[:'asn']
      end

      if attributes.key?(:'org')
        self.org = attributes[:'org']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@ip_address.nil? && @ip_address.to_s.length > 15
        invalid_properties.push('invalid value for "ip_address", the character length must be smaller than or equal to 15.')
      end

      if !@ip_address.nil? && @ip_address.to_s.length < 7
        invalid_properties.push('invalid value for "ip_address", the character length must be greater than or equal to 7.')
      end

      pattern = Regexp.new(/^(\d{1,3}\.){3}\d{1,3}$/)
      if !@ip_address.nil? && @ip_address !~ pattern
        invalid_properties.push("invalid value for \"ip_address\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^AS\d+$/)
      if !@asn.nil? && @asn !~ pattern
        invalid_properties.push("invalid value for \"asn\", must conform to the pattern #{pattern}.")
      end

      if !@country.nil? && @country.to_s.length > 2
        invalid_properties.push('invalid value for "country", the character length must be smaller than or equal to 2.')
      end

      if !@country.nil? && @country.to_s.length < 2
        invalid_properties.push('invalid value for "country", the character length must be greater than or equal to 2.')
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if !@country.nil? && @country !~ pattern
        invalid_properties.push("invalid value for \"country\", must conform to the pattern #{pattern}.")
      end

      if !@region.nil? && @region.to_s.length > 60
        invalid_properties.push('invalid value for "region", the character length must be smaller than or equal to 60.')
      end

      if !@region.nil? && @region.to_s.length < 2
        invalid_properties.push('invalid value for "region", the character length must be greater than or equal to 2.')
      end

      if !@city.nil? && @city.to_s.length > 60
        invalid_properties.push('invalid value for "city", the character length must be smaller than or equal to 60.')
      end

      if !@city.nil? && @city.to_s.length < 2
        invalid_properties.push('invalid value for "city", the character length must be greater than or equal to 2.')
      end

      if !@postal_code.nil? && @postal_code.to_s.length > 10
        invalid_properties.push('invalid value for "postal_code", the character length must be smaller than or equal to 10.')
      end

      if !@postal_code.nil? && @postal_code.to_s.length < 2
        invalid_properties.push('invalid value for "postal_code", the character length must be greater than or equal to 2.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@ip_address.nil? && @ip_address.to_s.length > 15
      return false if !@ip_address.nil? && @ip_address.to_s.length < 7
      return false if !@ip_address.nil? && @ip_address !~ Regexp.new(/^(\d{1,3}\.){3}\d{1,3}$/)
      ip_version_validator = EnumAttributeValidator.new('String', ["ipv4", "ipv6"])
      return false unless ip_version_validator.valid?(@ip_version)
      return false if !@asn.nil? && @asn !~ Regexp.new(/^AS\d+$/)
      return false if !@country.nil? && @country.to_s.length > 2
      return false if !@country.nil? && @country.to_s.length < 2
      return false if !@country.nil? && @country !~ Regexp.new(/^[A-Z]{2}$/)
      return false if !@region.nil? && @region.to_s.length > 60
      return false if !@region.nil? && @region.to_s.length < 2
      return false if !@city.nil? && @city.to_s.length > 60
      return false if !@city.nil? && @city.to_s.length < 2
      return false if !@postal_code.nil? && @postal_code.to_s.length > 10
      return false if !@postal_code.nil? && @postal_code.to_s.length < 2
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ip_address Value to be assigned
    def ip_address=(ip_address)
      if ip_address.to_s.length > 15
        fail ArgumentError, 'invalid value for "ip_address", the character length must be smaller than or equal to 15.'
      end

      if ip_address.to_s.length < 7
        fail ArgumentError, 'invalid value for "ip_address", the character length must be greater than or equal to 7.'
      end

      pattern = Regexp.new(/^(\d{1,3}\.){3}\d{1,3}$/)
      if ip_address !~ pattern
        fail ArgumentError, "invalid value for \"ip_address\", must conform to the pattern #{pattern}."
      end

      @ip_address = ip_address
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ip_version Object to be assigned
    def ip_version=(ip_version)
      validator = EnumAttributeValidator.new('String', ["ipv4", "ipv6"])
      unless validator.valid?(ip_version)
        fail ArgumentError, "invalid value for \"ip_version\", must be one of #{validator.allowable_values}."
      end
      @ip_version = ip_version
    end

    # Custom attribute writer method with validation
    # @param [Object] asn Value to be assigned
    def asn=(asn)
      pattern = Regexp.new(/^AS\d+$/)
      if asn !~ pattern
        fail ArgumentError, "invalid value for \"asn\", must conform to the pattern #{pattern}."
      end

      @asn = asn
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      if country.to_s.length > 2
        fail ArgumentError, 'invalid value for "country", the character length must be smaller than or equal to 2.'
      end

      if country.to_s.length < 2
        fail ArgumentError, 'invalid value for "country", the character length must be greater than or equal to 2.'
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if country !~ pattern
        fail ArgumentError, "invalid value for \"country\", must conform to the pattern #{pattern}."
      end

      @country = country
    end

    # Custom attribute writer method with validation
    # @param [Object] region Value to be assigned
    def region=(region)
      if region.to_s.length > 60
        fail ArgumentError, 'invalid value for "region", the character length must be smaller than or equal to 60.'
      end

      if region.to_s.length < 2
        fail ArgumentError, 'invalid value for "region", the character length must be greater than or equal to 2.'
      end

      @region = region
    end

    # Custom attribute writer method with validation
    # @param [Object] city Value to be assigned
    def city=(city)
      if city.to_s.length > 60
        fail ArgumentError, 'invalid value for "city", the character length must be smaller than or equal to 60.'
      end

      if city.to_s.length < 2
        fail ArgumentError, 'invalid value for "city", the character length must be greater than or equal to 2.'
      end

      @city = city
    end

    # Custom attribute writer method with validation
    # @param [Object] postal_code Value to be assigned
    def postal_code=(postal_code)
      if postal_code.to_s.length > 10
        fail ArgumentError, 'invalid value for "postal_code", the character length must be smaller than or equal to 10.'
      end

      if postal_code.to_s.length < 2
        fail ArgumentError, 'invalid value for "postal_code", the character length must be greater than or equal to 2.'
      end

      @postal_code = postal_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ip_address == o.ip_address &&
          ipv6 == o.ipv6 &&
          ip_version == o.ip_version &&
          ip_prefix == o.ip_prefix &&
          asn == o.asn &&
          org == o.org &&
          company == o.company &&
          country == o.country &&
          region == o.region &&
          city == o.city &&
          postal_code == o.postal_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ip_address, ipv6, ip_version, ip_prefix, asn, org, company, country, region, city, postal_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
