=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.4
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Lightweight, fraud-relevant item context representing a single cart entry. Omits heavy marketing assets (images, HTML copy) to prioritize low-latency authorization. 
  class LineItem < ApiModelBase
    # Platform-agnostic line item or cart item identifier. Supports standard alphanumeric IDs, Fortress identifiers (li_...), and GraphQL GIDs (gid://shopify/LineItem/12345). 
    attr_accessor :id

    # Merchant SKU, barcode, or variant identifier.
    attr_accessor :sku

    # Concise product or item title.
    attr_accessor :title

    attr_accessor :category

    # Quantity of the item being purchased.
    attr_accessor :quantity

    # Price per unit in the order currency.
    attr_accessor :unit_price

    # Optional gross line total (unitPrice * quantity) before item discounts.
    attr_accessor :total_amount

    # Indicates whether this item is fulfilled digitally without physical delivery.
    attr_accessor :is_digital

    # Indicates whether this item is a cash-equivalent stored value card or code.
    attr_accessor :is_gift_card

    # Whether this item requires physical dispatch to a postal address.
    attr_accessor :requires_shipping

    # Brand or manufacturer name (used for high-value resale targeting).
    attr_accessor :brand

    # Public HTTP/HTTPS URL of the product image for review consoles.
    attr_accessor :image_url

    # Flexible container for storefront-specific variant traits (e.g. size, color).
    attr_accessor :metadata

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'sku' => :'sku',
        :'title' => :'title',
        :'category' => :'category',
        :'quantity' => :'quantity',
        :'unit_price' => :'unitPrice',
        :'total_amount' => :'totalAmount',
        :'is_digital' => :'isDigital',
        :'is_gift_card' => :'isGiftCard',
        :'requires_shipping' => :'requiresShipping',
        :'brand' => :'brand',
        :'image_url' => :'imageUrl',
        :'metadata' => :'metadata'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'sku' => :'String',
        :'title' => :'String',
        :'category' => :'ItemCategoryEnum',
        :'quantity' => :'Integer',
        :'unit_price' => :'Float',
        :'total_amount' => :'Float',
        :'is_digital' => :'Boolean',
        :'is_gift_card' => :'Boolean',
        :'requires_shipping' => :'Boolean',
        :'brand' => :'String',
        :'image_url' => :'String',
        :'metadata' => :'Hash<String, Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::LineItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::LineItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'sku')
        self.sku = attributes[:'sku']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      else
        self.quantity = nil
      end

      if attributes.key?(:'unit_price')
        self.unit_price = attributes[:'unit_price']
      else
        self.unit_price = nil
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      end

      if attributes.key?(:'is_digital')
        self.is_digital = attributes[:'is_digital']
      end

      if attributes.key?(:'is_gift_card')
        self.is_gift_card = attributes[:'is_gift_card']
      end

      if attributes.key?(:'requires_shipping')
        self.requires_shipping = attributes[:'requires_shipping']
      end

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@id.nil? && @id.to_s.length > 128
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 128.')
      end

      if !@id.nil? && @id.to_s.length < 1
        invalid_properties.push('invalid value for "id", the character length must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.:\/]{1,128}$/)
      if !@id.nil? && @id !~ pattern
        invalid_properties.push("invalid value for \"id\", must conform to the pattern #{pattern}.")
      end

      if !@sku.nil? && @sku.to_s.length > 64
        invalid_properties.push('invalid value for "sku", the character length must be smaller than or equal to 64.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.]{1,64}$/)
      if !@sku.nil? && @sku !~ pattern
        invalid_properties.push("invalid value for \"sku\", must conform to the pattern #{pattern}.")
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @title.to_s.length > 255
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 255.')
      end

      if @title.to_s.length < 1
        invalid_properties.push('invalid value for "title", the character length must be greater than or equal to 1.')
      end

      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      if @quantity > 10000
        invalid_properties.push('invalid value for "quantity", must be smaller than or equal to 10000.')
      end

      if @quantity < 1
        invalid_properties.push('invalid value for "quantity", must be greater than or equal to 1.')
      end

      if @unit_price.nil?
        invalid_properties.push('invalid value for "unit_price", unit_price cannot be nil.')
      end

      if @unit_price > 1.0E+7
        invalid_properties.push('invalid value for "unit_price", must be smaller than or equal to 1.0E+7.')
      end

      if @unit_price < 0.0
        invalid_properties.push('invalid value for "unit_price", must be greater than or equal to 0.0.')
      end

      if !@total_amount.nil? && @total_amount > 1.0E+7
        invalid_properties.push('invalid value for "total_amount", must be smaller than or equal to 1.0E+7.')
      end

      if !@total_amount.nil? && @total_amount < 0.0
        invalid_properties.push('invalid value for "total_amount", must be greater than or equal to 0.0.')
      end

      if !@brand.nil? && @brand.to_s.length > 128
        invalid_properties.push('invalid value for "brand", the character length must be smaller than or equal to 128.')
      end

      if !@image_url.nil? && @image_url.to_s.length > 2048
        invalid_properties.push('invalid value for "image_url", the character length must be smaller than or equal to 2048.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@id.nil? && @id.to_s.length > 128
      return false if !@id.nil? && @id.to_s.length < 1
      return false if !@id.nil? && @id !~ Regexp.new(/^[a-zA-Z0-9_\-\.:\/]{1,128}$/)
      return false if !@sku.nil? && @sku.to_s.length > 64
      return false if !@sku.nil? && @sku !~ Regexp.new(/^[a-zA-Z0-9_\-\.]{1,64}$/)
      return false if @title.nil?
      return false if @title.to_s.length > 255
      return false if @title.to_s.length < 1
      return false if @quantity.nil?
      return false if @quantity > 10000
      return false if @quantity < 1
      return false if @unit_price.nil?
      return false if @unit_price > 1.0E+7
      return false if @unit_price < 0.0
      return false if !@total_amount.nil? && @total_amount > 1.0E+7
      return false if !@total_amount.nil? && @total_amount < 0.0
      return false if !@brand.nil? && @brand.to_s.length > 128
      return false if !@image_url.nil? && @image_url.to_s.length > 2048
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.to_s.length > 128
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 128.'
      end

      if id.to_s.length < 1
        fail ArgumentError, 'invalid value for "id", the character length must be greater than or equal to 1.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.:\/]{1,128}$/)
      if id !~ pattern
        fail ArgumentError, "invalid value for \"id\", must conform to the pattern #{pattern}."
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] sku Value to be assigned
    def sku=(sku)
      if sku.to_s.length > 64
        fail ArgumentError, 'invalid value for "sku", the character length must be smaller than or equal to 64.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.]{1,64}$/)
      if sku !~ pattern
        fail ArgumentError, "invalid value for \"sku\", must conform to the pattern #{pattern}."
      end

      @sku = sku
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end
      if title.to_s.length > 255
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 255.'
      end

      if title.to_s.length < 1
        fail ArgumentError, 'invalid value for "title", the character length must be greater than or equal to 1.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] quantity Value to be assigned
    def quantity=(quantity)
      if quantity.nil?
        fail ArgumentError, 'quantity cannot be nil'
      end
      if quantity > 10000
        fail ArgumentError, 'invalid value for "quantity", must be smaller than or equal to 10000.'
      end

      if quantity < 1
        fail ArgumentError, 'invalid value for "quantity", must be greater than or equal to 1.'
      end

      @quantity = quantity
    end

    # Custom attribute writer method with validation
    # @param [Object] unit_price Value to be assigned
    def unit_price=(unit_price)
      if unit_price.nil?
        fail ArgumentError, 'unit_price cannot be nil'
      end
      if unit_price > 1.0E+7
        fail ArgumentError, 'invalid value for "unit_price", must be smaller than or equal to 1.0E+7.'
      end

      if unit_price < 0.0
        fail ArgumentError, 'invalid value for "unit_price", must be greater than or equal to 0.0.'
      end

      @unit_price = unit_price
    end

    # Custom attribute writer method with validation
    # @param [Object] total_amount Value to be assigned
    def total_amount=(total_amount)
      if total_amount > 1.0E+7
        fail ArgumentError, 'invalid value for "total_amount", must be smaller than or equal to 1.0E+7.'
      end

      if total_amount < 0.0
        fail ArgumentError, 'invalid value for "total_amount", must be greater than or equal to 0.0.'
      end

      @total_amount = total_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] brand Value to be assigned
    def brand=(brand)
      if brand.to_s.length > 128
        fail ArgumentError, 'invalid value for "brand", the character length must be smaller than or equal to 128.'
      end

      @brand = brand
    end

    # Custom attribute writer method with validation
    # @param [Object] image_url Value to be assigned
    def image_url=(image_url)
      if image_url.to_s.length > 2048
        fail ArgumentError, 'invalid value for "image_url", the character length must be smaller than or equal to 2048.'
      end

      @image_url = image_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          sku == o.sku &&
          title == o.title &&
          category == o.category &&
          quantity == o.quantity &&
          unit_price == o.unit_price &&
          total_amount == o.total_amount &&
          is_digital == o.is_digital &&
          is_gift_card == o.is_gift_card &&
          requires_shipping == o.requires_shipping &&
          brand == o.brand &&
          image_url == o.image_url &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, sku, title, category, quantity, unit_price, total_amount, is_digital, is_gift_card, requires_shipping, brand, image_url, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
