=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.9
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Order context for the purchase.
  class OrderContext < ApiModelBase
    # Unique identifier for the order.
    attr_accessor :order_id

    # Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
    attr_accessor :order_total

    # Shipping method for the order.
    attr_accessor :shipping_method

    # Number of items in the order.
    attr_accessor :line_item_count

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'order_id' => :'orderId',
        :'order_total' => :'orderTotal',
        :'shipping_method' => :'shippingMethod',
        :'line_item_count' => :'lineItemCount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'order_id' => :'String',
        :'order_total' => :'Float',
        :'shipping_method' => :'String',
        :'line_item_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::OrderContext` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::OrderContext`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'order_total')
        self.order_total = attributes[:'order_total']
      end

      if attributes.key?(:'shipping_method')
        self.shipping_method = attributes[:'shipping_method']
      end

      if attributes.key?(:'line_item_count')
        self.line_item_count = attributes[:'line_item_count']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@order_total.nil? && @order_total > 1.0E+7
        invalid_properties.push('invalid value for "order_total", must be smaller than or equal to 1.0E+7.')
      end

      if !@order_total.nil? && @order_total < 0.01
        invalid_properties.push('invalid value for "order_total", must be greater than or equal to 0.01.')
      end

      if !@line_item_count.nil? && @line_item_count > 100
        invalid_properties.push('invalid value for "line_item_count", must be smaller than or equal to 100.')
      end

      if !@line_item_count.nil? && @line_item_count < 0
        invalid_properties.push('invalid value for "line_item_count", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@order_total.nil? && @order_total > 1.0E+7
      return false if !@order_total.nil? && @order_total < 0.01
      shipping_method_validator = EnumAttributeValidator.new('String', ["digital", "ship", "bopis"])
      return false unless shipping_method_validator.valid?(@shipping_method)
      return false if !@line_item_count.nil? && @line_item_count > 100
      return false if !@line_item_count.nil? && @line_item_count < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] order_total Value to be assigned
    def order_total=(order_total)
      if order_total.nil?
        fail ArgumentError, 'order_total cannot be nil'
      end

      if order_total > 1.0E+7
        fail ArgumentError, 'invalid value for "order_total", must be smaller than or equal to 1.0E+7.'
      end

      if order_total < 0.01
        fail ArgumentError, 'invalid value for "order_total", must be greater than or equal to 0.01.'
      end

      @order_total = order_total
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] shipping_method Object to be assigned
    def shipping_method=(shipping_method)
      validator = EnumAttributeValidator.new('String', ["digital", "ship", "bopis"])
      unless validator.valid?(shipping_method)
        fail ArgumentError, "invalid value for \"shipping_method\", must be one of #{validator.allowable_values}."
      end
      @shipping_method = shipping_method
    end

    # Custom attribute writer method with validation
    # @param [Object] line_item_count Value to be assigned
    def line_item_count=(line_item_count)
      if line_item_count.nil?
        fail ArgumentError, 'line_item_count cannot be nil'
      end

      if line_item_count > 100
        fail ArgumentError, 'invalid value for "line_item_count", must be smaller than or equal to 100.'
      end

      if line_item_count < 0
        fail ArgumentError, 'invalid value for "line_item_count", must be greater than or equal to 0.'
      end

      @line_item_count = line_item_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          order_id == o.order_id &&
          order_total == o.order_total &&
          shipping_method == o.shipping_method &&
          line_item_count == o.line_item_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [order_id, order_total, shipping_method, line_item_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
