=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.2
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  class PaymentWalletTypeEnum
    PAYPAL = "paypal".freeze
    APPLE_PAY = "apple_pay".freeze
    GOOGLE_PAY = "google_pay".freeze
    CASH_APP = "cash_app".freeze
    VENMO = "venmo".freeze
    LINK = "link".freeze
    SHOP_PAY = "shop_pay".freeze
    AMAZON_PAY = "amazon_pay".freeze
    SAMSUNG_PAY = "samsung_pay".freeze
    OTHER = "other".freeze

    def self.all_vars
      @all_vars ||= [PAYPAL, APPLE_PAY, GOOGLE_PAY, CASH_APP, VENMO, LINK, SHOP_PAY, AMAZON_PAY, SAMSUNG_PAY, OTHER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PaymentWalletTypeEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PaymentWalletTypeEnum"
    end
  end

end
