=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.1
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # RFC 7807 Problem Details
  class Problem < ApiModelBase
    # A URI reference that identifies the problem type.
    attr_accessor :type

    # A short, human-readable summary of the problem type.
    attr_accessor :title

    # The HTTP status code applicable to this problem.
    attr_accessor :status

    # Human-readable explanation specific to this occurrence.
    attr_accessor :detail

    # A URI reference that identifies the specific occurrence.
    attr_accessor :instance

    # Application-specific error code.
    attr_accessor :error_code

    # Server-generated trace ID for debugging.
    attr_accessor :trace_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'title' => :'title',
        :'status' => :'status',
        :'detail' => :'detail',
        :'instance' => :'instance',
        :'error_code' => :'errorCode',
        :'trace_id' => :'traceId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'title' => :'String',
        :'status' => :'Integer',
        :'detail' => :'String',
        :'instance' => :'String',
        :'error_code' => :'String',
        :'trace_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::Problem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::Problem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 'about:blank'
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'detail')
        self.detail = attributes[:'detail']
      end

      if attributes.key?(:'instance')
        self.instance = attributes[:'instance']
      end

      if attributes.key?(:'error_code')
        self.error_code = attributes[:'error_code']
      end

      if attributes.key?(:'trace_id')
        self.trace_id = attributes[:'trace_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@title.nil? && @title.to_s.length > 100
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 100.')
      end

      if !@title.nil? && @title.to_s.length < 3
        invalid_properties.push('invalid value for "title", the character length must be greater than or equal to 3.')
      end

      if !@status.nil? && @status > 599
        invalid_properties.push('invalid value for "status", must be smaller than or equal to 599.')
      end

      if !@status.nil? && @status < 100
        invalid_properties.push('invalid value for "status", must be greater than or equal to 100.')
      end

      if !@detail.nil? && @detail.to_s.length > 1024
        invalid_properties.push('invalid value for "detail", the character length must be smaller than or equal to 1024.')
      end

      if !@detail.nil? && @detail.to_s.length < 3
        invalid_properties.push('invalid value for "detail", the character length must be greater than or equal to 3.')
      end

      if !@instance.nil? && @instance.to_s.length > 1024
        invalid_properties.push('invalid value for "instance", the character length must be smaller than or equal to 1024.')
      end

      if !@instance.nil? && @instance.to_s.length < 1
        invalid_properties.push('invalid value for "instance", the character length must be greater than or equal to 1.')
      end

      if !@error_code.nil? && @error_code.to_s.length > 50
        invalid_properties.push('invalid value for "error_code", the character length must be smaller than or equal to 50.')
      end

      if !@error_code.nil? && @error_code.to_s.length < 3
        invalid_properties.push('invalid value for "error_code", the character length must be greater than or equal to 3.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@title.nil? && @title.to_s.length > 100
      return false if !@title.nil? && @title.to_s.length < 3
      return false if !@status.nil? && @status > 599
      return false if !@status.nil? && @status < 100
      return false if !@detail.nil? && @detail.to_s.length > 1024
      return false if !@detail.nil? && @detail.to_s.length < 3
      return false if !@instance.nil? && @instance.to_s.length > 1024
      return false if !@instance.nil? && @instance.to_s.length < 1
      return false if !@error_code.nil? && @error_code.to_s.length > 50
      return false if !@error_code.nil? && @error_code.to_s.length < 3
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.to_s.length > 100
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 100.'
      end

      if title.to_s.length < 3
        fail ArgumentError, 'invalid value for "title", the character length must be greater than or equal to 3.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status > 599
        fail ArgumentError, 'invalid value for "status", must be smaller than or equal to 599.'
      end

      if status < 100
        fail ArgumentError, 'invalid value for "status", must be greater than or equal to 100.'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] detail Value to be assigned
    def detail=(detail)
      if detail.to_s.length > 1024
        fail ArgumentError, 'invalid value for "detail", the character length must be smaller than or equal to 1024.'
      end

      if detail.to_s.length < 3
        fail ArgumentError, 'invalid value for "detail", the character length must be greater than or equal to 3.'
      end

      @detail = detail
    end

    # Custom attribute writer method with validation
    # @param [Object] instance Value to be assigned
    def instance=(instance)
      if instance.to_s.length > 1024
        fail ArgumentError, 'invalid value for "instance", the character length must be smaller than or equal to 1024.'
      end

      if instance.to_s.length < 1
        fail ArgumentError, 'invalid value for "instance", the character length must be greater than or equal to 1.'
      end

      @instance = instance
    end

    # Custom attribute writer method with validation
    # @param [Object] error_code Value to be assigned
    def error_code=(error_code)
      if error_code.to_s.length > 50
        fail ArgumentError, 'invalid value for "error_code", the character length must be smaller than or equal to 50.'
      end

      if error_code.to_s.length < 3
        fail ArgumentError, 'invalid value for "error_code", the character length must be greater than or equal to 3.'
      end

      @error_code = error_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          title == o.title &&
          status == o.status &&
          detail == o.detail &&
          instance == o.instance &&
          error_code == o.error_code &&
          trace_id == o.trace_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, title, status, detail, instance, error_code, trace_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
