=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.2.10
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module AlogramPayRisk
  # Interaction batch signal variant (one or more user interactions).
  class SignalsInteractionVariant < ApiModelBase
    # Value for interaction signals.
    attr_accessor :signal_type

    attr_accessor :entities

    # One or more interactions associated with the signal.
    attr_accessor :interactions

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'signal_type' => :'signalType',
        :'entities' => :'entities',
        :'interactions' => :'interactions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'signal_type' => :'String',
        :'entities' => :'EntityIds',
        :'interactions' => :'Array<Interaction>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AlogramPayRisk::SignalsInteractionVariant` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AlogramPayRisk::SignalsInteractionVariant`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'signal_type')
        self.signal_type = attributes[:'signal_type']
      else
        self.signal_type = nil
      end

      if attributes.key?(:'entities')
        self.entities = attributes[:'entities']
      else
        self.entities = nil
      end

      if attributes.key?(:'interactions')
        if (value = attributes[:'interactions']).is_a?(Array)
          self.interactions = value
        end
      else
        self.interactions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @signal_type.nil?
        invalid_properties.push('invalid value for "signal_type", signal_type cannot be nil.')
      end

      if @entities.nil?
        invalid_properties.push('invalid value for "entities", entities cannot be nil.')
      end

      if @interactions.nil?
        invalid_properties.push('invalid value for "interactions", interactions cannot be nil.')
      end

      if @interactions.length > 1000
        invalid_properties.push('invalid value for "interactions", number of items must be less than or equal to 1000.')
      end

      if @interactions.length < 1
        invalid_properties.push('invalid value for "interactions", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @signal_type.nil?
      signal_type_validator = EnumAttributeValidator.new('String', ["interaction"])
      return false unless signal_type_validator.valid?(@signal_type)
      return false if @entities.nil?
      return false if @interactions.nil?
      return false if @interactions.length > 1000
      return false if @interactions.length < 1
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] signal_type Object to be assigned
    def signal_type=(signal_type)
      validator = EnumAttributeValidator.new('String', ["interaction"])
      unless validator.valid?(signal_type)
        fail ArgumentError, "invalid value for \"signal_type\", must be one of #{validator.allowable_values}."
      end
      @signal_type = signal_type
    end

    # Custom attribute writer method with validation
    # @param [Object] entities Value to be assigned
    def entities=(entities)
      if entities.nil?
        fail ArgumentError, 'entities cannot be nil'
      end

      @entities = entities
    end

    # Custom attribute writer method with validation
    # @param [Object] interactions Value to be assigned
    def interactions=(interactions)
      if interactions.nil?
        fail ArgumentError, 'interactions cannot be nil'
      end
      if interactions.length > 1000
        fail ArgumentError, 'invalid value for "interactions", number of items must be less than or equal to 1000.'
      end

      if interactions.length < 1
        fail ArgumentError, 'invalid value for "interactions", number of items must be greater than or equal to 1.'
      end

      @interactions = interactions
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          signal_type == o.signal_type &&
          entities == o.entities &&
          interactions == o.interactions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [signal_type, entities, interactions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
