=begin
#Alogram PayRisk Engine

#Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

The version of the OpenAPI document: 0.3.2
Contact: packages@alogram.ai
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'set'

# Common files
require 'alogram_payrisk/api_client'
require 'alogram_payrisk/api_error'
require 'alogram_payrisk/api_model_base'
require 'alogram_payrisk/version'
require 'alogram_payrisk/configuration'

# Models
AlogramPayRisk.autoload :Account, 'alogram_payrisk/models/account'
AlogramPayRisk.autoload :AccountCheckRequest, 'alogram_payrisk/models/account_check_request'
AlogramPayRisk.autoload :AgentManifest, 'alogram_payrisk/models/agent_manifest'
AlogramPayRisk.autoload :AgentProvider, 'alogram_payrisk/models/agent_provider'
AlogramPayRisk.autoload :AuthContext, 'alogram_payrisk/models/auth_context'
AlogramPayRisk.autoload :AvsResultEnum, 'alogram_payrisk/models/avs_result_enum'
AlogramPayRisk.autoload :BankTransfer, 'alogram_payrisk/models/bank_transfer'
AlogramPayRisk.autoload :Card, 'alogram_payrisk/models/card'
AlogramPayRisk.autoload :CardNetworkEnum, 'alogram_payrisk/models/card_network_enum'
AlogramPayRisk.autoload :CategorySignal, 'alogram_payrisk/models/category_signal'
AlogramPayRisk.autoload :ChannelEnum, 'alogram_payrisk/models/channel_enum'
AlogramPayRisk.autoload :CheckRequest, 'alogram_payrisk/models/check_request'
AlogramPayRisk.autoload :ConfidenceEnum, 'alogram_payrisk/models/confidence_enum'
AlogramPayRisk.autoload :Crypto, 'alogram_payrisk/models/crypto'
AlogramPayRisk.autoload :CvvResultEnum, 'alogram_payrisk/models/cvv_result_enum'
AlogramPayRisk.autoload :DecisionResolutionRequest, 'alogram_payrisk/models/decision_resolution_request'
AlogramPayRisk.autoload :DecisionResolutionRequestAnalyst, 'alogram_payrisk/models/decision_resolution_request_analyst'
AlogramPayRisk.autoload :DecisionResolutionResponse, 'alogram_payrisk/models/decision_resolution_response'
AlogramPayRisk.autoload :DecisionResponse, 'alogram_payrisk/models/decision_response'
AlogramPayRisk.autoload :DecisionResponsePolicy, 'alogram_payrisk/models/decision_response_policy'
AlogramPayRisk.autoload :DeviceInfo, 'alogram_payrisk/models/device_info'
AlogramPayRisk.autoload :DiscountCode, 'alogram_payrisk/models/discount_code'
AlogramPayRisk.autoload :EntityIds, 'alogram_payrisk/models/entity_ids'
AlogramPayRisk.autoload :EntryMethodEnum, 'alogram_payrisk/models/entry_method_enum'
AlogramPayRisk.autoload :ExternalAssessment, 'alogram_payrisk/models/external_assessment'
AlogramPayRisk.autoload :FraudScore, 'alogram_payrisk/models/fraud_score'
AlogramPayRisk.autoload :Identity, 'alogram_payrisk/models/identity'
AlogramPayRisk.autoload :IngestPaymentEvent202Response, 'alogram_payrisk/models/ingest_payment_event202_response'
AlogramPayRisk.autoload :Integrity, 'alogram_payrisk/models/integrity'
AlogramPayRisk.autoload :Interaction, 'alogram_payrisk/models/interaction'
AlogramPayRisk.autoload :InteractionTypeEnum, 'alogram_payrisk/models/interaction_type_enum'
AlogramPayRisk.autoload :Invoice, 'alogram_payrisk/models/invoice'
AlogramPayRisk.autoload :IpInfo, 'alogram_payrisk/models/ip_info'
AlogramPayRisk.autoload :KycCheckRequest, 'alogram_payrisk/models/kyc_check_request'
AlogramPayRisk.autoload :KycPayload, 'alogram_payrisk/models/kyc_payload'
AlogramPayRisk.autoload :MerchantContext, 'alogram_payrisk/models/merchant_context'
AlogramPayRisk.autoload :OperatorType, 'alogram_payrisk/models/operator_type'
AlogramPayRisk.autoload :OrderContext, 'alogram_payrisk/models/order_context'
AlogramPayRisk.autoload :PayerTypeEnum, 'alogram_payrisk/models/payer_type_enum'
AlogramPayRisk.autoload :PaymentAuthorizationOutcome, 'alogram_payrisk/models/payment_authorization_outcome'
AlogramPayRisk.autoload :PaymentCaptureOutcome, 'alogram_payrisk/models/payment_capture_outcome'
AlogramPayRisk.autoload :PaymentCardTypeEnum, 'alogram_payrisk/models/payment_card_type_enum'
AlogramPayRisk.autoload :PaymentChargeback, 'alogram_payrisk/models/payment_chargeback'
AlogramPayRisk.autoload :PaymentChargebackOutcome, 'alogram_payrisk/models/payment_chargeback_outcome'
AlogramPayRisk.autoload :PaymentDisputeOutcome, 'alogram_payrisk/models/payment_dispute_outcome'
AlogramPayRisk.autoload :PaymentEvent, 'alogram_payrisk/models/payment_event'
AlogramPayRisk.autoload :PaymentEventType, 'alogram_payrisk/models/payment_event_type'
AlogramPayRisk.autoload :PaymentMethod, 'alogram_payrisk/models/payment_method'
AlogramPayRisk.autoload :PaymentOutcome, 'alogram_payrisk/models/payment_outcome'
AlogramPayRisk.autoload :PaymentRealtimeTypeEnum, 'alogram_payrisk/models/payment_realtime_type_enum'
AlogramPayRisk.autoload :PaymentRefundOutcome, 'alogram_payrisk/models/payment_refund_outcome'
AlogramPayRisk.autoload :PaymentWalletTypeEnum, 'alogram_payrisk/models/payment_wallet_type_enum'
AlogramPayRisk.autoload :PostalAddress, 'alogram_payrisk/models/postal_address'
AlogramPayRisk.autoload :Problem, 'alogram_payrisk/models/problem'
AlogramPayRisk.autoload :Purchase, 'alogram_payrisk/models/purchase'
AlogramPayRisk.autoload :PurchaseInitiatorEnum, 'alogram_payrisk/models/purchase_initiator_enum'
AlogramPayRisk.autoload :PurchaseSequenceEnum, 'alogram_payrisk/models/purchase_sequence_enum'
AlogramPayRisk.autoload :PurchaseUsageEnum, 'alogram_payrisk/models/purchase_usage_enum'
AlogramPayRisk.autoload :Realtime, 'alogram_payrisk/models/realtime'
AlogramPayRisk.autoload :ReasonDetail, 'alogram_payrisk/models/reason_detail'
AlogramPayRisk.autoload :RiskBreakdown, 'alogram_payrisk/models/risk_breakdown'
AlogramPayRisk.autoload :RiskCategoryEnum, 'alogram_payrisk/models/risk_category_enum'
AlogramPayRisk.autoload :RiskLevelEnum, 'alogram_payrisk/models/risk_level_enum'
AlogramPayRisk.autoload :ScaMethodEnum, 'alogram_payrisk/models/sca_method_enum'
AlogramPayRisk.autoload :ScoreRecord, 'alogram_payrisk/models/score_record'
AlogramPayRisk.autoload :ScoresSuccessResponse, 'alogram_payrisk/models/scores_success_response'
AlogramPayRisk.autoload :SignalsAccountVariant, 'alogram_payrisk/models/signals_account_variant'
AlogramPayRisk.autoload :SignalsInteractionVariant, 'alogram_payrisk/models/signals_interaction_variant'
AlogramPayRisk.autoload :SignalsRequest, 'alogram_payrisk/models/signals_request'
AlogramPayRisk.autoload :StoredCredentialContext, 'alogram_payrisk/models/stored_credential_context'
AlogramPayRisk.autoload :ThreeDSData, 'alogram_payrisk/models/three_ds_data'
AlogramPayRisk.autoload :Wallet, 'alogram_payrisk/models/wallet'

# APIs
AlogramPayRisk.autoload :ForensicDataApi, 'alogram_payrisk/api/forensic_data_api'
AlogramPayRisk.autoload :RiskScoringApi, 'alogram_payrisk/api/risk_scoring_api'
AlogramPayRisk.autoload :RoadmapPreviewApi, 'alogram_payrisk/api/roadmap_preview_api'
AlogramPayRisk.autoload :SignalIntelligenceApi, 'alogram_payrisk/api/signal_intelligence_api'
AlogramPayRisk.autoload :SystemApi, 'alogram_payrisk/api/system_api'

module AlogramPayRisk
  class << self
    # Customize default settings for the SDK using block.
    #   AlogramPayRisk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
